steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['-c', gcloud secrets versions access latest --secret=test > /root/.ssh/id_rsa']
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - -c
  - |
    chmod 600 /root/.ssh/config
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/id_rsa
    EOF
    ssh-keygen -t rsa github.com > /root/.ssh/known-hosts
    cat /root/.ssh/id_rsa
    cat /root/.ssh/config
  volumes:
  - name: 'ssh'
    path: /root/.ssh